"""empty message

Revision ID: 06cab35fa0ad
Revises: 73ebb475603a
Create Date: 2026-05-26 20:11:21.191416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06cab35fa0ad'
down_revision: Union[str, Sequence[str], None] = '73ebb475603a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_participants', sa.Column('gold_earned', sa.Integer(), nullable=False))
    op.add_column('match_participants', sa.Column('gold_spent', sa.Integer(), nullable=False))
    op.add_column('match_participants', sa.Column('total_damage_dealt', sa.Integer(), nullable=False))
    op.add_column('match_participants', sa.Column('total_damage_taken', sa.Integer(), nullable=False))
    op.add_column('match_participants', sa.Column('total_dd_to_champions', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('game_start_timestamp', sa.DateTime(timezone=True), nullable=False))
    op.add_column('matches', sa.Column('game_end_timestamp', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('matches', 'id')
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('players', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('players', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('matches', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('matches', 'game_end_timestamp')
    op.drop_column('matches', 'game_start_timestamp')
    op.drop_column('match_participants', 'total_dd_to_champions')
    op.drop_column('match_participants', 'total_damage_taken')
    op.drop_column('match_participants', 'total_damage_dealt')
    op.drop_column('match_participants', 'gold_spent')
    op.drop_column('match_participants', 'gold_earned')
    # ### end Alembic commands ###
