"""init_db

Revision ID: 6d813d65d605
Revises: 
Create Date: 2026-05-27 03:36:54.024473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d813d65d605'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=40), nullable=False),
    sa.Column('game_version', sa.String(length=20), nullable=False),
    sa.Column('game_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_end_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('game_name', sa.Text(), nullable=False),
    sa.Column('tag_line', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index('idx_game_name_tag_line', 'players', ['game_name', 'tag_line'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('queue_type', sa.String(length=30), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.String(length=10), nullable=False),
    sa.Column('league_points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=40), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('gold_spent', sa.Integer(), nullable=False),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=False),
    sa.Column('total_damage_taken', sa.Integer(), nullable=False),
    sa.Column('total_dd_to_champions', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('team_position', sa.String(length=20), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_participants_champion_id'), 'match_participants', ['champion_id'], unique=False)
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_puuid'), 'match_participants', ['puuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_participants_puuid'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_champion_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_table('leagues')
    op.drop_index('idx_game_name_tag_line', table_name='players')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
