"""empty message

Revision ID: 73ebb475603a
Revises: 8c49229f8289
Create Date: 2026-05-26 17:56:57.512922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ebb475603a'
down_revision: Union[str, Sequence[str], None] = '8c49229f8289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('players', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'id')
    op.drop_column('matches', 'id')
    # ### end Alembic commands ###
